[package]
name = "rstest"
version = "0.5.0"
authors = ["Abderrahim AZIME <azime_1@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
