[package]
name = "rstest"
version = "githubflow_get_new_version --release-type minor --remote-name origin"
authors = ["Abderrahim AZIME <azime_1@yahoo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
