name: Publish release

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test job
        run: echo "test release"

      - name: install httpie dependency
        run: |
          apt-get update
          apt install -y httpie

      - name: Install requirements
        run: apt-get install -y curl wget build-essential
