name: Publish release

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test job
      run: echo "test release"

    - name: install httpie dependency
      run: |
        sudo apt-get update
        sudo apt install -y httpie

