name: Publish release

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: test job
      run: echo "test release"

    - name: create packages_0.zip
      run: zip packages_0.zip test*
    - name: create packages_1.zip
      run: zip packages_1.zip test*

    - name: upload packages_0 packages
      uses: actions/upload-artifact@v1
      with:
        name: packages_0
        path: "packages_0.zip"

    - name: upload packages_1 packages
      uses: actions/upload-artifact@v1
      with:
        name: packages_1
        path: "packages_1.zip"
