name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: test job
      run: echo "test release"

    - name: Generate Changelog
      run: echo "# Good things have arrived" > ${{ github.workflow }}-CHANGELOG.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body_path: ${{ github.workflow }}-CHANGELOG.txt
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
