name: Share variables between jobs

on: [push]
jobs:
  job1:
    name: test1
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.version_output }}
    steps:
      - id: Checkout
        uses: actions/checkout@v3
        with:
          submodules : recursive
          fetch-depth: 0
      - id: version
        run: |
          v=$(git describe --tags)
          echo "version_output=$v" >> $GITHUB_OUTPUT
          echo "************************"
          echo "$v"
          t=$(1/0)
          echo "************************"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          VV: ${{needs.job1.outputs.VERSION}}
        run: echo "$VV"

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: |
      always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
    steps:
      - run: echo "${{ toJSON(needs) }}"