name: AA

on:
  pull_request:
jobs:
  job1:
    name: test1
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.version.outputs.version_output }}
    steps:
      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master

      - name: version
        run: |
          docker --version
